---
- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_group_members }}"
  #loop: "{{ lookup('dict', docker_group_members, wantlist=True) }}"
